local predictor and RPC batch interface unified
PaddlePaddle/Serving pull request #821
Opened 2020-09-02 12:21 UTC by wangjiawei04

2020-09-04 12:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/Serving?pullRequest=821) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/Serving?pullRequest=821) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: wangjiawei04<br/>:x: root<br/><hr/>**root** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/Serving?pullRequest=821) it.</sub>

2020-09-09 06:34 UTC, barrierye commented on python/pipeline/operator.py
> +                            service_handler = local_rpc_service_handler.LocalPredictorServiceHandler(
local_rpc_service_handler 是不是考虑改成 local_service_handler 会好一些

2020-09-13 04:33 UTC, guru4elephant requested changes
please improve this PR.

2020-09-13 04:33 UTC, guru4elephant commented on core/general-server/op/general_reader_op.cpp
>    // specify the memory needed for output tensor_vector
这里为什么写死batch_size=1?

2020-09-13 04:33 UTC, guru4elephant commented on doc/PIPELINE_OP.md
> +rpc模式的原理是启动一个rpc服务，客户端用protobuf格式打包预测请求的内容，在rpc服务端完成预测。适合稳定性较高的场景，web服务和预测服务可以解耦合实现多地部署。
`web服务和预测服务可以解耦合实现多地部署`，这一句看不出来和前面的关系，web服务的概念是不是需要先介绍一下。

2020-09-13 04:33 UTC, guru4elephant commented on doc/PIPELINE_OP.md
> +local predictor的原理是启动一个python的predictor，客户端可以直接调用python的predictor来实现。适合快速迭代以及规模较小的场景，web服务和预测服务需要在同一台机器上，
此处是否应该画一个示意图，将web服务，rpc服务，local predictor三者不同的组合关系表示一下；

2020-09-13 04:33 UTC, guru4elephant commented on doc/PIPELINE_OP.md
> +在web模式下，我们通过配置Op的方式来配置每一个Serving模型。
`配置每一个Serving模型`，此处是否应该说明是local_predictor模型，还是rpc模型，或者是两者都包含；此外Serving模型这个概念有点宽泛，是否需要具体化；

2020-09-13 04:33 UTC, guru4elephant commented on doc/PIPELINE_OP.md
> +我们以OCR的识别模型作为例子，以下是RecOp的实现。
请先解释RecOp的具体作用

2020-09-13 04:33 UTC, guru4elephant commented on doc/PIPELINE_OP.md
> +在做好init_op，preprocess和postprocess这些函数的重载之后，我们就在调用这个Op的地方去控制rpc和local predictor。
`去控制rpc和local predictor` -> `去控制rpc或local predictor`？

2020-09-13 04:33 UTC, guru4elephant commented on doc/PIPELINE_OP.md
> +在上面的例子可以看到，当我们在Op的构造函数里，指定了server_endpoints和client_config时，就会采用rpc的方式。因为这些在运算Op的时候需要先执行preprocess，然后访问rpc服务请求预测，最后再执行postprocess。请求预测的过程，可能预测服务在本地，也可能在远端，可能是单点可能是分布式，需要给出对应的IP地址作为server_endpoints
`预测服务在本地`，这个说法是否能够更具体，比如说在Web服务的实例本地运行之类的。只是说预测服务在本地，看起来像发生在请求端一样。

2020-09-13 04:33 UTC, guru4elephant commented on doc/PIPELINE_OP.md
> +rec_op = RecOp(
分成两段代码？

2020-09-13 04:33 UTC, guru4elephant commented on python/examples/lac/lac_client.py
> +    fetch_map = client.predict(
增加words.lod属于不兼容升级，用户不设置是否会与此前的示例行为一致？

2020-09-13 04:33 UTC, guru4elephant commented on python/pipeline/local_rpc_service_handler.py
> +        from paddle_serving_app.local_predict import Debugger
Debugger -> LocalPredictor

2020-09-13 04:33 UTC, guru4elephant commented on python/pipeline/operator.py
> +    def init_client(self, client_config, server_endpoints, fetch_names):
有两个问题：1）能否直接从server_endpoints获取client_config，达到客户端无须配置config的目的；2）fetch_name如果不是最终请求的时候指定的名字，只是一个fetch list全集，是否可以去掉；

2020-09-13 04:33 UTC, guru4elephant commented on tools/serving_build.sh
> +            #check_cmd "python lac_web_service.py lac_model/ lac_workdir 9292 &"
remove if you do not need this

2020-09-13 04:33 UTC, guru4elephant commented on tools/serving_build.sh
> +    #unset SERVING_BIN
remove if not needed.

2020-09-13 04:33 UTC, guru4elephant commented on tools/serving_build.sh
> +    #unset SERVING_BIN
remove if not needed.

2020-09-13 04:33 UTC, guru4elephant commented on tools/serving_build.sh
> +    #unset SERVING_BIN
remove if not needed.

2020-09-13 04:33 UTC, guru4elephant commented on tools/serving_build.sh
> +    #unset SERVING_BIN
remove if not needed.

2020-09-13 04:33 UTC, guru4elephant commented on tools/serving_build.sh
> +    #unset SERVING_BIN
remove if not needed.

2020-09-13 04:33 UTC, guru4elephant commented on tools/serving_build.sh
> +    #unset SERVING_BIN
remove if not needed.

2020-12-06 16:25 UTC, closed without merging